/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Adaptater.ListeLogAdaptater;
import Adaptater.ListeLogDateAdapdater;
import Adaptater.ListeNoeudAdaptater;
import Services.LogServices;
import Services.NoeudService;
import entity.Noeud;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Yassine
 */
public class Accueil extends javax.swing.JFrame {

    Noeud noeudamodifier=null;
    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        setIcon();
        Ajouter.setVisible(false);
        afficher.setVisible(false);
        consulter.setVisible(false);
        lister.setVisible(false);
        modifier.setVisible(false);
        find.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbledPane = new javax.swing.JTabbedPane();
        accueilPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        ConsulterLog = new javax.swing.JButton();
        listerLog = new javax.swing.JButton();
        nePanel = new javax.swing.JPanel();
        ajouterNoeud = new javax.swing.JButton();
        afficherNoeud = new javax.swing.JButton();
        Ajouter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tflogin = new javax.swing.JTextField();
        labelpwd = new javax.swing.JLabel();
        tfpwd = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonRetourAjouter = new javax.swing.JButton();
        afficher = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeNoeudTable = new javax.swing.JTable();
        jButtonRetourAfficher = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        consulter = new javax.swing.JPanel();
        jButtonRetourConsulter = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConsulterButton = new javax.swing.JButton();
        lister = new javax.swing.JPanel();
        jButtonRetourLister = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeLogTable = new javax.swing.JTable();
        modifier = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfnom1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfIP1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tflogin1 = new javax.swing.JTextField();
        labelpwd1 = new javax.swing.JLabel();
        tfpwd1 = new javax.swing.JTextField();
        jButtonModifierSubmit = new javax.swing.JButton();
        jButtonRetourModifier = new javax.swing.JButton();
        find = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDate = new javax.swing.JTable();
        FindRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout accueilPanelLayout = new javax.swing.GroupLayout(accueilPanel);
        accueilPanel.setLayout(accueilPanelLayout);
        accueilPanelLayout.setHorizontalGroup(
            accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        accueilPanelLayout.setVerticalGroup(
            accueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        JTabbledPane.addTab("Accueil", accueilPanel);

        ConsulterLog.setText("Consulter les logs");
        ConsulterLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterLogActionPerformed(evt);
            }
        });

        listerLog.setText("Lister les logs");
        listerLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listerLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsulterLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listerLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ConsulterLog)
                .addGap(44, 44, 44)
                .addComponent(listerLog)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        JTabbledPane.addTab("Log History", logPanel);

        ajouterNoeud.setText("Ajouter noeud");
        ajouterNoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterNoeudActionPerformed(evt);
            }
        });

        afficherNoeud.setText("Afficher les noeuds");
        afficherNoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherNoeudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nePanelLayout = new javax.swing.GroupLayout(nePanel);
        nePanel.setLayout(nePanelLayout);
        nePanelLayout.setHorizontalGroup(
            nePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nePanelLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(nePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ajouterNoeud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afficherNoeud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(185, 185, 185))
        );
        nePanelLayout.setVerticalGroup(
            nePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ajouterNoeud)
                .addGap(40, 40, 40)
                .addComponent(afficherNoeud)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        JTabbledPane.addTab("Noeud", nePanel);

        jLabel1.setText("Nom : ");

        jLabel2.setText("IP : ");

        jLabel3.setText("Login : ");

        labelpwd.setText("Password : ");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonRetourAjouter.setText("Retour");
        jButtonRetourAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjouterLayout = new javax.swing.GroupLayout(Ajouter);
        Ajouter.setLayout(AjouterLayout);
        AjouterLayout.setHorizontalGroup(
            AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(labelpwd))
                .addGap(25, 25, 25)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfnom)
                    .addComponent(tfIP)
                    .addComponent(tflogin)
                    .addComponent(tfpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjouterLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jButtonRetourAjouter)
                .addGap(29, 29, 29)
                .addComponent(jButtonAjouter)
                .addGap(55, 55, 55))
        );
        AjouterLayout.setVerticalGroup(
            AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tflogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpwd)
                    .addComponent(tfpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonRetourAjouter))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ListeNoeudTable.setModel(new ListeNoeudAdaptater());
        jScrollPane1.setViewportView(ListeNoeudTable);

        jButtonRetourAfficher.setText("Retour");
        jButtonRetourAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourAfficherActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afficherLayout = new javax.swing.GroupLayout(afficher);
        afficher.setLayout(afficherLayout);
        afficherLayout.setHorizontalGroup(
            afficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(afficherLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonRetourAfficher)
                .addGap(49, 49, 49)
                .addComponent(jButtonModifier)
                .addGap(48, 48, 48)
                .addComponent(jButtonSupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        afficherLayout.setVerticalGroup(
            afficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afficherLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(afficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetourAfficher)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButtonRetourConsulter.setText("Retour");
        jButtonRetourConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourConsulterActionPerformed(evt);
            }
        });

        jLabel7.setText("From :");

        jLabel8.setText("To :");

        ConsulterButton.setText("Consulter");
        ConsulterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consulterLayout = new javax.swing.GroupLayout(consulter);
        consulter.setLayout(consulterLayout);
        consulterLayout.setHorizontalGroup(
            consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consulterLayout.createSequentialGroup()
                .addGroup(consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consulterLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consulterLayout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(jButtonRetourConsulter)
                        .addGap(57, 57, 57)))
                .addGroup(consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConsulterButton)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57))
        );
        consulterLayout.setVerticalGroup(
            consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consulterLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(consulterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsulterButton)
                    .addComponent(jButtonRetourConsulter))
                .addGap(83, 83, 83))
        );

        jButtonRetourLister.setText("Retour");
        jButtonRetourLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourListerActionPerformed(evt);
            }
        });

        listeLogTable.setModel(new ListeLogAdaptater());
        jScrollPane2.setViewportView(listeLogTable);

        javax.swing.GroupLayout listerLayout = new javax.swing.GroupLayout(lister);
        lister.setLayout(listerLayout);
        listerLayout.setHorizontalGroup(
            listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(listerLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButtonRetourLister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listerLayout.setVerticalGroup(
            listerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listerLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetourLister)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel4.setText("Nom : ");

        jLabel5.setText("IP : ");

        jLabel6.setText("Login : ");

        labelpwd1.setText("Password : ");

        jButtonModifierSubmit.setText("Modifier");
        jButtonModifierSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierSubmitActionPerformed(evt);
            }
        });

        jButtonRetourModifier.setText("Retour");
        jButtonRetourModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifierLayout = new javax.swing.GroupLayout(modifier);
        modifier.setLayout(modifierLayout);
        modifierLayout.setHorizontalGroup(
            modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifierLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(labelpwd1))
                .addGap(25, 25, 25)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfnom1)
                    .addComponent(tfIP1)
                    .addComponent(tflogin1)
                    .addComponent(tfpwd1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifierLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jButtonRetourModifier)
                .addGap(29, 29, 29)
                .addComponent(jButtonModifierSubmit)
                .addGap(55, 55, 55))
        );
        modifierLayout.setVerticalGroup(
            modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifierLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tflogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpwd1)
                    .addComponent(tfpwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(modifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifierSubmit)
                    .addComponent(jButtonRetourModifier))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tableDate.setModel(new ListeLogDateAdapdater());
        jScrollPane3.setViewportView(tableDate);

        FindRetour.setText("Retour");
        FindRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findLayout = new javax.swing.GroupLayout(find);
        find.setLayout(findLayout);
        findLayout.setHorizontalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addGroup(findLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(FindRetour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        findLayout.setVerticalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FindRetour)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbledPane)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(afficher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consulter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(229, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbledPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(afficher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consulter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterNoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterNoeudActionPerformed
        Ajouter.setVisible(true);
        JTabbledPane.setVisible(false);
    }//GEN-LAST:event_ajouterNoeudActionPerformed

    private void afficherNoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherNoeudActionPerformed
        afficher.setVisible(true);
        JTabbledPane.setVisible(false);
        ListeNoeudTable.setModel(new ListeNoeudAdaptater());
    }//GEN-LAST:event_afficherNoeudActionPerformed

    private void ConsulterLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterLogActionPerformed
        consulter.setVisible(true);
        JTabbledPane.setVisible(false);
    }//GEN-LAST:event_ConsulterLogActionPerformed

    private void listerLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listerLogActionPerformed
        lister.setVisible(true);
        JTabbledPane.setVisible(false);

    }//GEN-LAST:event_listerLogActionPerformed

    private void jButtonRetourAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourAjouterActionPerformed
        Ajouter.setVisible(false);
        JTabbledPane.setVisible(true);
    }//GEN-LAST:event_jButtonRetourAjouterActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        Noeud ne = new Noeud();
        NoeudService nes = new NoeudService();
        ne.setIp(tfIP.getText());
        ne.setLogin(tflogin.getText());
        ne.setName(tfnom.getText());
        ne.setPwd(tfpwd.getText());
        if (nes.ajouterNoeud(ne)) {
            JOptionPane.showMessageDialog(null,
                    "Ajout effectué avec succes !",
                    "Notification",
                    JOptionPane.INFORMATION_MESSAGE);
            JTabbledPane.setVisible(true);
            Ajouter.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null,
                    "Erreur lors de l'ajout",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonRetourAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourAfficherActionPerformed
        afficher.setVisible(false);
        JTabbledPane.setVisible(true);
    }//GEN-LAST:event_jButtonRetourAfficherActionPerformed

    private void jButtonRetourListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourListerActionPerformed
        lister.setVisible(false);
        JTabbledPane.setVisible(true);
    }//GEN-LAST:event_jButtonRetourListerActionPerformed

    private void jButtonRetourConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourConsulterActionPerformed
        consulter.setVisible(false);
        JTabbledPane.setVisible(true);
    }//GEN-LAST:event_jButtonRetourConsulterActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        int ligne = ListeNoeudTable.getSelectedRow();//Si tu veut la ligne selectionnée
        //int colonne = listeLogTable.getSelectedColumn();//Si tu veut la colonne selectionnée
        if (ligne != -1) {
            Object celluleNom = ListeNoeudTable.getValueAt(ligne, 0);
            Object celluleIp = ListeNoeudTable.getValueAt(ligne, 1);
            Object celluleUsername = ListeNoeudTable.getValueAt(ligne, 2);
            Object cellulePassword = ListeNoeudTable.getValueAt(ligne, 3);

            NoeudService nes = new NoeudService();

            Noeud ne = nes.rechercherNoeud(celluleNom.toString(), celluleIp.toString(), celluleUsername.toString(), cellulePassword.toString());

            if (nes.supprimerNoeud(ne)) {
                JOptionPane.showMessageDialog(null,
                        "Suppression effectuée avec succes !",
                        "Notification",
                        JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null,
                        "Erreur lors de la suppression",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE);
            }
            ListeNoeudTable.setModel(new ListeNoeudAdaptater());
        } else {
            JOptionPane.showMessageDialog(null,
                    "Vous devez selectionner un noeud !",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed

        int ligne = ListeNoeudTable.getSelectedRow();//Si tu veut la ligne selectionnée
        //int colonne = listeLogTable.getSelectedColumn();//Si tu veut la colonne selectionnée
        if (ligne != -1) {
            Object celluleNom = ListeNoeudTable.getValueAt(ligne, 0);
            Object celluleIp = ListeNoeudTable.getValueAt(ligne, 1);
            Object celluleUsername = ListeNoeudTable.getValueAt(ligne, 2);
            Object cellulePassword = ListeNoeudTable.getValueAt(ligne, 3);

            NoeudService nes = new NoeudService();

            noeudamodifier = nes.rechercherNoeud(celluleNom.toString(), celluleIp.toString(), celluleUsername.toString(), cellulePassword.toString());
            tfnom1.setText(noeudamodifier.getName());
            tfIP1.setText(noeudamodifier.getIp());
            tflogin1.setText(noeudamodifier.getLogin());
            tfpwd1.setText(noeudamodifier.getPwd());
            modifier.setVisible(true);
            afficher.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null,
                    "Vous devez selectionner un noeud !",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonModifierSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierSubmitActionPerformed
        NoeudService nes = new NoeudService();
        noeudamodifier.setIp(tfIP1.getText());
        noeudamodifier.setLogin(tflogin1.getText());
        noeudamodifier.setName(tfnom1.getText());
        noeudamodifier.setPwd(tfpwd1.getText());
        if (nes.modifierNoeud(noeudamodifier)) {
            JOptionPane.showMessageDialog(null,
                    "modification effectuée avec succes !",
                    "Notification",
                    JOptionPane.INFORMATION_MESSAGE);
            JTabbledPane.setVisible(true);
            modifier.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null,
                    "Erreur lors de la modification",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModifierSubmitActionPerformed

    private void jButtonRetourModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourModifierActionPerformed
        afficher.setVisible(true);
        modifier.setVisible(false);
    }//GEN-LAST:event_jButtonRetourModifierActionPerformed

    private void ConsulterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterButtonActionPerformed
        if(toDate.getDate()==null&&fromDate.getDate()==null){
            JOptionPane.showMessageDialog(null,
                    "Vous devez choisir au moins une date !",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            
        }else{
            find.setVisible(true);
            tableDate.setModel(new ListeLogDateAdapdater(fromDate.getDate(), toDate.getDate()));
            consulter.setVisible(false);
        }
    }//GEN-LAST:event_ConsulterButtonActionPerformed

    private void FindRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindRetourActionPerformed
        find.setVisible(false);
        consulter.setVisible(true);
        fromDate.setDate(null);
        toDate.setDate(null);
    }//GEN-LAST:event_FindRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Accueil().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ajouter;
    private javax.swing.JButton ConsulterButton;
    private javax.swing.JButton ConsulterLog;
    private javax.swing.JButton FindRetour;
    private javax.swing.JTabbedPane JTabbledPane;
    private javax.swing.JTable ListeNoeudTable;
    private javax.swing.JPanel accueilPanel;
    private javax.swing.JPanel afficher;
    private javax.swing.JButton afficherNoeud;
    private javax.swing.JButton ajouterNoeud;
    private javax.swing.JPanel consulter;
    private javax.swing.JPanel find;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonModifierSubmit;
    private javax.swing.JButton jButtonRetourAfficher;
    private javax.swing.JButton jButtonRetourAjouter;
    private javax.swing.JButton jButtonRetourConsulter;
    private javax.swing.JButton jButtonRetourLister;
    private javax.swing.JButton jButtonRetourModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelpwd;
    private javax.swing.JLabel labelpwd1;
    private javax.swing.JTable listeLogTable;
    private javax.swing.JPanel lister;
    private javax.swing.JButton listerLog;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel modifier;
    private javax.swing.JPanel nePanel;
    private javax.swing.JTable tableDate;
    private javax.swing.JTextField tfIP;
    private javax.swing.JTextField tfIP1;
    private javax.swing.JTextField tflogin;
    private javax.swing.JTextField tflogin1;
    private javax.swing.JTextField tfnom;
    private javax.swing.JTextField tfnom1;
    private javax.swing.JTextField tfpwd;
    private javax.swing.JTextField tfpwd1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.jpg")) );
    }
}
